spring.application.name=demo

# 1. H2 DB ?? ??
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. H2 ?? ?? ?? (??? DB ?? ??)
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# 3. JPA ?? (?? ? ? DB ???? ???? ????!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=VlwEyVlPKZ6yV9yH3Yf0wz5w9z4x8y7a6b5c4d3e2f1g0h9i8j7k6l5m4n3o2p1